### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by sinuso** [aandrew-me/tgpt#121]
```
:~$ tgpt -q hello
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getMainText({0xc0004ec1b0?, 0xc0004cd002?})
        /home/runner/work/tgpt/tgpt/functions.go:470 +0x105
main.getSilentText({0x7ffeceb43746, 0x4}, {0x3?, 0x857204?})
        /home/runner/work/tgpt/tgpt/functions.go:430 +0x19f
main.main()
        /home/runner/work/tgpt/tgpt/main.go:76 +0x5e7
:~$

```

```
:~$ tgpt -w hello
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getMainText({0xc0000a81f0?, 0xc0000e0002?})
        /home/runner/work/tgpt/tgpt/functions.go:470 +0x105
main.getWholeText({0x7ffe3dc2f745, 0x5}, {0x3?, 0x857204?})
        /home/runner/work/tgpt/tgpt/functions.go:398 +0x1aa
main.main()
        /home/runner/work/tgpt/tgpt/main.go:61 +0x3e5
:~$

```

```
:~$ tgpt hello
hello



:~$

```

**Comment by razimantv** [comment]
I get the same error when I run queries with flags. Without flags, I get an empty output so that might be part of the problem.

**Comment by Prabhat-Kumar-42** [comment]
getting same error as mentioned - really needs to be fixed

**Comment by aandrew-me** [comment]
Looks like the API is crossing the rate limits :(

**Comment by sinuso** [comment]
It's working again! Thank @aandrew-me

**Comment by aandrew-me** [comment]
Yes I changed api,  if you see error message related to rate limit, wait a few seconds and try again
