### ISSUE TITLE
NEW- execute shell command option not working :ubuntu bash etc

### ISSUE THREAD

**Issue by Free-Radical** [aandrew-me/tgpt#122]
I'm guessing backend' wisend up and keeps jamming incoming requests

```

$ tgpt "How to update my system?"
How to update my system?



$ tgpt -s "How to update my system?"
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getMainText({0xc0001b2240?, 0xc0000fe002?})
        /home/runner/work/tgpt/tgpt/functions.go:470 +0x105
main.getCommand({0xc000210240, 0x22c})
        /home/runner/work/tgpt/tgpt/functions.go:281 +0x22a
main.shellCommand({0x7ffdfbf1e238, 0x18})
        /home/runner/work/tgpt/tgpt/functions.go:246 +0x1aa
main.main()
        /home/runner/work/tgpt/tgpt/main.go:92 +0x80b
$

```

**Comment by Free-Radical** [comment]
@aandrew-me I have an to possibly solve that might solve this once and for all , how do we chat privately???

**Comment by aandrew-me** [comment]
> @aandrew-me I have an to possibly solve that might solve this once and for all , how do we chat privately???

You can message me on telegram - t.me/aandrew_me
