### ISSUE TITLE
@web_search at Phind model makes tgpt crash

### ISSUE THREAD

**Issue by vimnux** [aandrew-me/tgpt#306]
Phind changed something today and now, the output of Phind's @web_search makes tgpt crash:

Command: `tgpt @web_search hi`

Gives output:
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/aandrew-me/tgpt/v2/providers/phind.GetMainText({0xc00044c500?, 0xc?})
	/build/tgpt/src/tgpt-2.8.1/providers/phind/phind.go:77 +0xe8
github.com/aandrew-me/tgpt/v2/providers.GetMainText({0xc00044c500?, 0xc000002038?}, {0x0?, 0xc00050e060?}, {0xc00005fc08?, 0xc0001cdf80?})
	/build/tgpt/src/tgpt-2.8.1/providers/providers.go:37 +0x114
main.handleEachPart(0xc0001729a0?, {0xc0000321e0, 0x30})
	/build/tgpt/src/tgpt-2.8.1/helper.go:352 +0x16e
main.makeRequestAndGetData({0xc0000321e0, 0x30}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:654 +0x3b8
main.getDataResponseTxt({0xc0000321e0?, 0xc0000321eb?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:44 +0x21d
main.getData({0xc0000321e0, 0x30}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:59 +0xa5
main.main()
	/build/tgpt/src/tgpt-2.8.1/main.go:344 +0x117a
```

The crash also occurs in interactive mode:

```
╭─ You
╰─> command to request a web search

╭─ Bot
To request a web search, you can use the following command:

@web_search <search_query>

For example, if you want to search for "Python tutorials", you would type:

@web_search Python tutorials

This will trigger my ability to perform a web search and provide you with
 relevant results. Is there a particular topic you'd like to search for?panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/aandrew-me/tgpt/v2/providers/phind.GetMainText({0xc00030f160?, 0xc?})
	/build/tgpt/src/tgpt-2.8.1/providers/phind/phind.go:77 +0xe8
github.com/aandrew-me/tgpt/v2/providers.GetMainText({0xc00030f160?, 0xc000312000?}, {0x0?, 0x1?}, {0x1?, 0x0?})
	/build/tgpt/src/tgpt-2.8.1/providers/providers.go:37 +0x114
main.handleEachPart(0xc000044a40?, {0xc00013c320, 0x1f})
	/build/tgpt/src/tgpt-2.8.1/helper.go:352 +0x16e
main.makeRequestAndGetData({0xc00013c320, 0x1f}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x7ffdb80557ef, 0x3}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:654 +0x3b8
main.getDataResponseTxt({0xc00013c320?, 0x56aa131bed80?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:44 +0x21d
main.getData({0xc00013c320, 0x1f}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/build/tgpt/src/tgpt-2.8.1/helper.go:59 +0xa5
main.main()
	/build/tgpt/src/tgpt-2.8.1/main.go:265 +0x1f2a
```

My tgpt version is up to date:
```
extra/tgpt 2.8.2-1 [installed: 2.8.1-1]
    AI Chatbots in terminal without needing API keys 
```

**Comment by vimnux** [comment]
Nevermind, Phind fixed it on their side.

**Comment by aandrew-me** [comment]
Yeah, however I found the piece of code where the program was crashing and changed it
