### ISSUE TITLE
FAIL: TestRequest- panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vt-alt** [aandrew-me/tgpt#318]
`go test -v ./...` fails with:
```
builder@x86_64:~/RPM/BUILD/tgpt-2.8.2$ go test -v ./...
?       github.com/aandrew-me/tgpt/v2   [no test files]
?       github.com/aandrew-me/tgpt/v2/client    [no test files]
?       github.com/aandrew-me/tgpt/v2/providers/blackboxai      [no test files]
?       github.com/aandrew-me/tgpt/v2/providers [no test files]
?       github.com/aandrew-me/tgpt/v2/providers/groq    [no test files]
?       github.com/aandrew-me/tgpt/v2/providers/duckduckgo      [no test files]
?       github.com/aandrew-me/tgpt/v2/providers/ollama  [no test files]
?       github.com/aandrew-me/tgpt/v2/providers/openai  [no test files]
?       github.com/aandrew-me/tgpt/v2/structs   [no test files]
?       github.com/aandrew-me/tgpt/v2/utils     [no test files]
=== RUN   TestRequest
--- FAIL: TestRequest (0.21s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8400fd]

goroutine 7 [running]:
testing.tRunner.func1.2({0x88b060, 0xca1c40})
        /usr/lib/golang/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /usr/lib/golang/src/testing/testing.go:1635 +0x35e
panic({0x88b060?, 0xca1c40?})
        /usr/lib/golang/src/runtime/panic.go:785 +0x132
github.com/aandrew-me/tgpt/v2/providers/koboldai.TestRequest(0xc0000dad00)
        /usr/src/RPM/BUILD/tgpt-2.8.2/providers/koboldai/koboldai_test.go:19 +0x7d
testing.tRunner(0xc0000dad00, 0x93eee0)
        /usr/lib/golang/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
        /usr/lib/golang/src/testing/testing.go:1743 +0x390
FAIL    github.com/aandrew-me/tgpt/v2/providers/koboldai        0.213s
=== RUN   TestRequest
--- FAIL: TestRequest (0.11s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8401e8]

goroutine 20 [running]:
testing.tRunner.func1.2({0x88b060, 0xca1c40})
        /usr/lib/golang/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /usr/lib/golang/src/testing/testing.go:1635 +0x35e
panic({0x88b060?, 0xca1c40?})
        /usr/lib/golang/src/runtime/panic.go:785 +0x132
github.com/aandrew-me/tgpt/v2/providers/phind.TestRequest(0xc000146b60)
        /usr/src/RPM/BUILD/tgpt-2.8.2/providers/phind/phind_test.go:14 +0x68
testing.tRunner(0xc000146b60, 0x93ef60)
        /usr/lib/golang/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
        /usr/lib/golang/src/testing/testing.go:1743 +0x390
FAIL    github.com/aandrew-me/tgpt/v2/providers/phind   0.111s
FAIL
builder@x86_64:~/RPM/BUILD/tgpt-2.8.2$ go version
go version go1.23.4 linux/amd64
```

**Comment by aandrew-me** [comment]
I fixed the issue, however I do not suggest to rely on tests, since a provider may not always work.

**Comment by vt-alt** [comment]
Thank you.
